[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "unsafe_function_mitigated"
version = "0.0.1"
requires-python = ">=3.9"

[project.scripts]
mitigated_app = "calculator:main"
